### ISSUE TITLE
Stripping of all credit to original authors (besides your rant) is incomplete.

### ISSUE THREAD

**Issue by danteoh** [taion/rrtr#9]
The string replace you used to replace all mention of "react-router" and @mjackson, @ryanflorence & co's work was incomplete.

You forgot to remove "React Router" as well, so it still shows up in the bottom of the docs.

Sure glad you published an entirely new project instead of properly forking too!

**Comment by tonyhb** [comment]
Definitely.

Also, creating a **new** repository and pushing up all existing code so it looks like a source sucks. Hit "fork" and show the world what it is: **a fork using other people's work** that you don't want to contribute back to any more.

**Comment by taion** [comment]
This was initially a fork. Unfortunately, code search doesn't work on forks; otherwise I would have set it up as such instead of as a source.

Note that I explicitly did not change the listing of authors on the package, nor do I assert any copyright there.

**Comment by evenstensberg** [comment]
@danteoh @tonyhb Let's clear up some core issues here: 

This repo was made to encourage innovation and futurism. As React-Router was, and still is open source, there's no stopping tweaking your repo as your own. @taion is just trying to make routing an even better experience. 

I don't really seem to get the point why you obviously are negative to this, based on your syntax composition. How does it help the open source community? Complaining about @taion actually doing hard work seems like something we read about in sarcastic Reddit threads, not in tools made for us to do the opposite.

**Comment by danteoh** [comment]
@ev1stensberg You don't think him publishing a medium post calling a project "dead" negative either?

**Comment by taion** [comment]
It's a common phrasal template – I think the epanalepsis works quite well rhetorically. Perhaps it comes off as more severe than it should without that context?

**Comment by evenstensberg** [comment]
I think that personal opinions of your developer experience should matter. @taion acted accordingly to Facebook's motto : "**Move fast, be bold**". Clearly some of the sentences could be eased up a bit, but I think this is rather about him trying to reach out through invoking through his frustration rather than seeming angry at React-Router as it is now.

**Comment by evenstensberg** [comment]
Also, I don't know get it why people are so angry. This is exactly what open source is about, making things, either it's an extension of someone else's work or if it's your own. If people wanted it not to be like this, you would have ended up paying to use 3rd party libraries, just because it needs to satisfy the author. That's 100% bullshit, and we all know it. Tweak, break, build.

You don't pay Ed Sheeran because you published a remake rather than a cover, do you?

**Comment by tonyhb** [comment]
1. This is going to affect people. If you depend on any of the router projects, such as relay support, you're going to have to change the router.
2. @taion is now going to have to backport fixes from react-router to here. That's double the work. It's already happened in #8, and it's highly ironic considering he's forking an "unmaintained" project.
3. There's now fragmentation in react router space; instead of contributing and making one router great there's now two competing routers.

The fragmentation and breaking of existing is the core issue here. JS has a lot of fragmentation as it is. This compounds it.

As an aside, contributing back and becoming a _core_ maintainer of the redux-router repo sounds like a great idea. From the blog post, the only evidence of a slow moving project is a series of messages not cutting a release, and a heavy handed reaction from it.

**Comment by taion** [comment]
@tonyhb 

That's not a backport. It's a bug fix that's not present upstream. Someone can choose to backport that to React Router – or not, it's not really up to me any more, since this entire feature has been reverted.

Keep in mind I've been the most active contributor to React Router by a large, large margin over the past several months: https://github.com/reactjs/react-router/pulse/monthly. It's not an inability to get my code merged that led me to make this fork.

In fact, at the current rate, it's not even a real division of effort, since I've been doing most of the work.

**Comment by tonyhb** [comment]
Okay cool. It's totally your prerogative to do this. I just dislike seeing fragmentation and breaking changes to projects; that's the main reason I'd love for there to be a reconciliation.

**Comment by taion** [comment]
Right.

Unfortunately, the current lack of direction and movement on the React Router project proper is not acceptable with respect to my objectives at work. That's why I felt the need to fork React Router in the first place.

The point is to _avoid_ large breaking changes (outside of, unfortunately, updating dependencies and library pointing) by updating and releasing on an incremental basis. I no longer have confidence that this is possible with the React Router project with the current project ownership.

**Comment by danteoh** [comment]
TBH I was mostly just trolling because of the medium article.  R-R is not dead, its just stable and slower moving than your needs.  Nowadays when I see "XXX is dead" I generally assume someone is going all left-pad on the open source community.

**Comment by taion** [comment]
Of course it's not dead. Like I said, I thought it was cute to follow the "the King is dead, long live the King" template.

And it's not a matter of being slower moving than my needs per se. The issue is that every release of React Router ends up being a major, breaking API change that requires users to rewrite large chunks of their code.

So yes, while React Router moves too slowly on things like bugfixes, performance improvements, and non-breaking feature additions, it also moves far too quickly on API churn.

**Comment by FrenchBen** [comment]
![179341_o](https://cloud.githubusercontent.com/assets/3965324/14446021/8daba86c-0006-11e6-838e-4412ce9dc1e1.gif)

**Comment by Daniel15** [comment]
> Also, creating a new repository and pushing up all existing code so it looks like a source sucks.

Is it actually an issue? The files all still blame to the original authors. It's not like @taion has made it look like he wrote all the code, or anything like that.

**Comment by quantuminformation** [comment]
React router, redux router, react-router-redux, rrtr.

How does one decide to pick a router these days?

**Comment by Daniel15** [comment]
> How does one decide to pick a router these days?

We could always make a project that uses the best features of every router. It could be called `react-rrtr-redux-router-router-historyjs-redux-extreme` 

I agree though, fragmentation is one of the major problems with JavaScript today. It's really hard to know which projects to use when there's a million different choices and most of them won't even exist any more a year from now. :confused:

**Comment by taion** [comment]
Use React Router. Sorry for the inconvenience here.
